-- ==========================================================================
-- Store Intelligence System — SQLite Schema
-- Task 3.2 — Follows TASKS.md exactly
-- ==========================================================================

-- -------------------------------------------------------------------------
-- events: all business events generated by the detector pipeline
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS events (
    id              INTEGER  PRIMARY KEY AUTOINCREMENT,
    event_id        TEXT     NOT NULL UNIQUE,
    store_id        TEXT     NOT NULL DEFAULT 'store_1',
    event_type      TEXT     NOT NULL,
    track_id        INTEGER  NOT NULL,
    timestamp       TEXT     NOT NULL,
    frame_no        INTEGER  NOT NULL,
    zone            TEXT     NOT NULL,
    dwell_seconds   REAL,
    metadata        TEXT,          -- JSON text
    created_at      TEXT     NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

-- -------------------------------------------------------------------------
-- visitors: deduplicated visitor records
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS visitors (
    id              INTEGER  PRIMARY KEY AUTOINCREMENT,
    track_id        INTEGER  NOT NULL UNIQUE,
    entry_time      TEXT,
    exit_time       TEXT,
    dwell_seconds   REAL,
    zones_visited   TEXT,          -- JSON text (array of zone names)
    is_staff        INTEGER  NOT NULL DEFAULT 0,   -- BOOLEAN: 0 = false, 1 = true
    signature       TEXT,          -- JSON text (appearance descriptor)
    created_at      TEXT     NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

-- -------------------------------------------------------------------------
-- zone_dwells: per-zone dwell records for each track
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS zone_dwells (
    id              INTEGER  PRIMARY KEY AUTOINCREMENT,
    track_id        INTEGER  NOT NULL,
    zone            TEXT     NOT NULL,
    entry_time      TEXT,
    exit_time       TEXT,
    dwell_seconds   REAL,
    created_at      TEXT     NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

-- -------------------------------------------------------------------------
-- recommendations: generated business recommendations
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS recommendations (
    id              INTEGER  PRIMARY KEY AUTOINCREMENT,
    rec_type        TEXT     NOT NULL,
    zone            TEXT,
    insight         TEXT     NOT NULL,
    action          TEXT     NOT NULL,
    severity        TEXT     NOT NULL DEFAULT 'medium',
    created_at      TEXT     NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

-- ==========================================================================
-- Indexes (as specified in TASKS.md Task 3.2)
-- ==========================================================================
CREATE INDEX IF NOT EXISTS idx_events_type       ON events(event_type);
CREATE INDEX IF NOT EXISTS idx_events_store      ON events(store_id);
CREATE INDEX IF NOT EXISTS idx_events_timestamp  ON events(timestamp);
CREATE INDEX IF NOT EXISTS idx_events_track      ON events(track_id);
CREATE INDEX IF NOT EXISTS idx_visitors_track    ON visitors(track_id);
CREATE INDEX IF NOT EXISTS idx_zone_dwells_zone  ON zone_dwells(zone);
CREATE INDEX IF NOT EXISTS idx_zone_dwells_track ON zone_dwells(track_id);
